name = "AutoChem"
uuid = "c8a5543f-d3ac-4b2a-a4ab-7a08b8c1d9c3"
authors = ["John Waczak <john.louis.waczak@gmail.com>"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
